version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: deps(go)
  groups:
    golang-x:
      patterns:
        - "golang.org/x/*"
    otel:
      patterns:
        - "go.opentelemetry.io/*"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: deps(docker)
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: deps(actions)
  groups:
    actions:
      patterns:
        - "actions/*"
