{
 "title": "Sagemcom F@st Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Usage",
   "type": "stat",
   "description": "Displays the data usage (down/up), as well as the change over the dashboard time range.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sagemcom_fast_optical_rx_bytes_total[$__range]))",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(increase(sagemcom_fast_optical_tx_bytes_total[$__range]))",
     "legendFormat": "Uploaded"
    }
   ]
  },
  {
   "title": "Current (bytes/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_optical_rx_bytes_total[$__rate_interval]))",
     "legendFormat": "⬇︎ (bytes/s)"
    },
    {
     "expr": "sum(rate(sagemcom_fast_optical_tx_bytes_total[$__rate_interval]))",
     "legendFormat": "⬆︎ (bytes/s)"
    },
    { "expression": "$A * 8", "type": "math" },
    { "expression": "$B * 8", "type": "math" }
   ]
  },
  {
   "title": "Max bitrate",
   "type": "stat",
   "description": "Displays the maximum instantaneous bitrate over the dashboard's time range",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(irate(sagemcom_fast_optical_rx_bytes_total[$__rate_interval]))[$__range:]) * 8",
     "legendFormat": "⬇︎"
    },
    {
     "expr": "max_over_time(sum(irate(sagemcom_fast_optical_tx_bytes_total[$__rate_interval]))[$__range:]) * 8",
     "legendFormat": "⬆︎"
    }
   ]
  },
  {
   "title": "Device Information",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sagemcom_fast_system_device_info) by (backup_software_version, gui_firmware_version, internal_firmware_version, mac_address, model_name, ont_serial_number, router_name, software_version, hardware_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WAN Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "WAN (Optical) Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_optical_rx_bytes_total[$__rate_interval])) by (name) * 8",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "sum(rate(sagemcom_fast_optical_tx_bytes_total[$__rate_interval])) by (name) * -1 * 8",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  {
   "title": "LAN (Ethernet) Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_ethernet_rx_bytes_total[$__rate_interval])) by (name) * 8 > 0",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "sum(rate(sagemcom_fast_ethernet_tx_bytes_total[$__rate_interval])) by (name) * -8 < 0",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Radio Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sagemcom_fast_wifi_radio_info) by (alias, name, regulatory_domain, supported_bandwidth, supported_standards)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSID Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sagemcom_fast_wifi_ssid_info) by (alias, name, radio, mac_address, ssid, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radio Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_wifi_ssid_rx_bytes_total{radio!=\"\"}[$__rate_interval])) by (radio) > 0",
     "legendFormat": "{{radio}} Rx"
    },
    {
     "expr": "sum(rate(sagemcom_fast_wifi_ssid_tx_bytes_total{radio!=\"\"}[$__rate_interval])) by (radio) * -1 < 0",
     "legendFormat": "{{radio}} Tx"
    }
   ]
  },
  {
   "title": "SSID Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_wifi_ssid_rx_bytes_total{ssid!=\"\"}[$__rate_interval])) by (ssid) > 0",
     "legendFormat": "{{ssid}} Rx"
    },
    {
     "expr": "sum(rate(sagemcom_fast_wifi_ssid_tx_bytes_total{ssid!=\"\"}[$__rate_interval])) by (ssid) * -1 < 0",
     "legendFormat": "{{ssid}} Tx"
    }
   ]
  },
  { "title": "Ethernet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Ethernet Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n    sagemcom_fast_ethernet_bitrate * on (name, alias, instance) group_left(cable_status, current_duplex_mode, mac_address, role, status) sagemcom_fast_ethernet_info\n) by (alias, cable_status, current_duplex_mode, mac_address, name, role, status)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethernet Bandwidth (bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_ethernet_rx_bytes_total[$__rate_interval])) by (name) > 0",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "sum(rate(sagemcom_fast_ethernet_tx_bytes_total[$__rate_interval])) by (name) * -1 < 0",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  {
   "title": "Ethernet Data Rate (packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_ethernet_rx_packets_total[$__rate_interval])) by (name) > 0",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "sum(rate(sagemcom_fast_ethernet_tx_packets_total[$__rate_interval])) by (name) * -1 < 0",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "System CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sagemcom_fast_resources_cpu_usage)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n    sum(sagemcom_fast_resources_total_memory_bytes)\n    -\n    sum(sagemcom_fast_resources_free_memory_bytes)\n)",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Flash usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sagemcom_fast_resources_used_flash_memory_bytes",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "description": "CPU time used per process aggregated by name, so some of these reflect multiple PIDs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(sagemcom_fast_resources_process_cpu_time_seconds[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Size",
   "type": "timeseries",
   "description": "Memory usage of each process - aggregated by name, so some of these reflect multiple PIDs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sagemcom_fast_resources_process_size_bytes) by (name)",
     "legendFormat": "{{name}} - {{pid}}"
    }
   ]
  },
  {
   "title": "Exporter Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape Durations (classic histogram)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum(increase(sagemcom_fast_exporter_collector_scrape_duration_seconds_bucket[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrape Durations (native histogram)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 70 },
     "targets": [
      {
       "expr": "sum(increase(sagemcom_fast_exporter_collector_scrape_duration_seconds[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrapes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum(increase(sagemcom_fast_exporter_collector_scrape_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "Scrapes"
      }
     ]
    },
    {
     "title": "Scrape Duration Quantile (classic)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sagemcom_fast_exporter_collector_scrape_duration_seconds_bucket[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrape Duration Quantile (native)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sagemcom_fast_exporter_collector_scrape_duration_seconds[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrape Success",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "sum(sagemcom_fast_exporter_collector_scrape_success) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 4, "w": 14, "x": 4, "y": 86 },
     "targets": [
      {
       "expr": "sum(sagemcom_fast_system_device_info) by (backup_software_version, gui_firmware_version, internal_firmware_version, mac_address, model_name, ont_serial_number, router_name, software_version, hardware_version)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}